# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec < Formula
  desc "Command-line interface for EdControls"
  homepage "https://github.com/dutchview/edcontrols-cli"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dutchview/edcontrols-cli/releases/download/v1.3.0/edcontrols-cli_1.3.0_darwin_amd64.tar.gz"
      sha256 "d6366a027fbbbabd12b82326aff32c0ba622f6e8bf83828efa37c81041d4b015"

      define_method(:install) do
        bin.install "ec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dutchview/edcontrols-cli/releases/download/v1.3.0/edcontrols-cli_1.3.0_darwin_arm64.tar.gz"
      sha256 "67d7b324a3f026cf311d04e2068aa0f0d27bb9e069b9cd23e4006ab4205f12f7"

      define_method(:install) do
        bin.install "ec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/edcontrols-cli/releases/download/v1.3.0/edcontrols-cli_1.3.0_linux_amd64.tar.gz"
      sha256 "cd81c84689f5fa1af2c2090d9445e03c5c14992721310b0f7d5253927e7105ca"
      define_method(:install) do
        bin.install "ec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/edcontrols-cli/releases/download/v1.3.0/edcontrols-cli_1.3.0_linux_arm64.tar.gz"
      sha256 "353f4482d3c6f662fd509df73a8a86a05c1ef1519dae2d06ff5d46ad968ccec4"
      define_method(:install) do
        bin.install "ec"
      end
    end
  end

  test do
    system "#{bin}/ec", "--version"
  end
end
