# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ec < Formula
  desc "Command-line interface for EdControls"
  homepage "https://github.com/dutchview/edcontrols-cli"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dutchview/edcontrols-cli/releases/download/v1.0.0/edcontrols-cli_1.0.0_darwin_amd64.tar.gz"
      sha256 "5f70b79496388c774b4822b7e77e5fe531ae8af29d8f181847e78a0ae0e3f976"

      def install
        bin.install "ec"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dutchview/edcontrols-cli/releases/download/v1.0.0/edcontrols-cli_1.0.0_darwin_arm64.tar.gz"
      sha256 "dd7e537eb8675a8d6411c510dcc2db726c82482c3f99fc9336ba29ae202d901e"

      def install
        bin.install "ec"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/edcontrols-cli/releases/download/v1.0.0/edcontrols-cli_1.0.0_linux_amd64.tar.gz"
      sha256 "b25a3e75e723d822d53498eca88ea192d2169f9fe72e4c1cfcbecc6b9e962293"
      def install
        bin.install "ec"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/edcontrols-cli/releases/download/v1.0.0/edcontrols-cli_1.0.0_linux_arm64.tar.gz"
      sha256 "01a380e35a5c6f9a01325ca7c3138fdff32fbbce079b8ef2da7c2c219c3bfa42"
      def install
        bin.install "ec"
      end
    end
  end

  test do
    system "#{bin}/ec", "--version"
  end
end
