# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hubspot < Formula
  desc "Command-line interface for HubSpot CRM"
  homepage "https://github.com/dutchview/hubspot-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.1.0/hubspot-cli_0.1.0_darwin_amd64.tar.gz"
      sha256 "6532d9943b87bcc7dbfee84f79f507368e5b5d56a3693cd5a0c8e801d7885584"

      define_method(:install) do
        bin.install "hubspot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.1.0/hubspot-cli_0.1.0_darwin_arm64.tar.gz"
      sha256 "685e40015f2b44058436d4161cda4010c4ea3bce100f9aec638b3ebf3731427d"

      define_method(:install) do
        bin.install "hubspot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.1.0/hubspot-cli_0.1.0_linux_amd64.tar.gz"
      sha256 "389f729bb3dd1e769c7eece9494bb1894fdbdfd587d4b0e1412fbd0a6ea321ea"
      define_method(:install) do
        bin.install "hubspot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.1.0/hubspot-cli_0.1.0_linux_arm64.tar.gz"
      sha256 "2134778ab0ce118bde9374abd5ba2825b29847ebced92f1cf344c52c6a3b10d5"
      define_method(:install) do
        bin.install "hubspot"
      end
    end
  end

  test do
    system "#{bin}/hubspot", "--version"
  end
end
