# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hubspot < Formula
  desc "Command-line interface for HubSpot CRM"
  homepage "https://github.com/dutchview/hubspot-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.2.0/hubspot-cli_0.2.0_darwin_amd64.tar.gz"
      sha256 "d4e932567aa1debdd217b5d122c2f76789c862b6fbf21081f0599c87a3ad0442"

      define_method(:install) do
        bin.install "hubspot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.2.0/hubspot-cli_0.2.0_darwin_arm64.tar.gz"
      sha256 "18e80ad56f10027de71e6b0708f6d53755fcd0e11eebab19f3ae16e0f3f37b3b"

      define_method(:install) do
        bin.install "hubspot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.2.0/hubspot-cli_0.2.0_linux_amd64.tar.gz"
      sha256 "4327fd370b32d26f5f488dd64936ee2f58c17559d6d1d2356b084bff7a26ac0c"
      define_method(:install) do
        bin.install "hubspot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.2.0/hubspot-cli_0.2.0_linux_arm64.tar.gz"
      sha256 "23b70b967ad443e5417d5a3f35a0354fd6cec7f797b85a309e2f28d274231171"
      define_method(:install) do
        bin.install "hubspot"
      end
    end
  end

  test do
    system "#{bin}/hubspot", "--version"
  end
end
