# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hubspot < Formula
  desc "Command-line interface for HubSpot CRM"
  homepage "https://github.com/dutchview/hubspot-cli"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.2.1/hubspot-cli_0.2.1_darwin_amd64.tar.gz"
      sha256 "4425aa4b5e6b7f99f32ce29bfb13999269d2bdcd421ccc527f8a18b43eb96190"

      define_method(:install) do
        bin.install "hubspot"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.2.1/hubspot-cli_0.2.1_darwin_arm64.tar.gz"
      sha256 "bf449a3c6fea6df6d70efd7bd95cd3aae22079385059a87e6cbca54157555758"

      define_method(:install) do
        bin.install "hubspot"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.2.1/hubspot-cli_0.2.1_linux_amd64.tar.gz"
      sha256 "a18bb7f225dafd24fb552f7427c5756bf05355ba3d74f127ddc9bb666deddb3d"
      define_method(:install) do
        bin.install "hubspot"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/hubspot-cli/releases/download/v0.2.1/hubspot-cli_0.2.1_linux_arm64.tar.gz"
      sha256 "47a19745f752d73bf1f66f85e7f859a45fa3d567744a8c6cbd367e8ae553d18d"
      define_method(:install) do
        bin.install "hubspot"
      end
    end
  end

  test do
    system "#{bin}/hubspot", "--version"
  end
end
