# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jira < Formula
  desc "Command-line interface for Jira Cloud"
  homepage "https://github.com/dutchview/jira-cli"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dutchview/jira-cli/releases/download/v0.6.0/jira-cli_0.6.0_darwin_amd64.tar.gz"
      sha256 "ec3fe63c938240e40a08b31fd2b762750de19920d13cd531a3350b1ec51ea3e6"

      define_method(:install) do
        bin.install "jira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dutchview/jira-cli/releases/download/v0.6.0/jira-cli_0.6.0_darwin_arm64.tar.gz"
      sha256 "2465c362621db806ac1b5e171c75fa15a7fa0cb39c256a268cf4868087e98063"

      define_method(:install) do
        bin.install "jira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/jira-cli/releases/download/v0.6.0/jira-cli_0.6.0_linux_amd64.tar.gz"
      sha256 "b5052f9580420480b51861c30a72bf482c8ebbdbbf0014523c5911d1199aebf9"
      define_method(:install) do
        bin.install "jira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dutchview/jira-cli/releases/download/v0.6.0/jira-cli_0.6.0_linux_arm64.tar.gz"
      sha256 "7af55da875d8d278f0b085b541dea7c56377b3fc8717fc04348d4f94a72efd74"
      define_method(:install) do
        bin.install "jira"
      end
    end
  end

  test do
    system "#{bin}/jira", "--version"
  end
end
